# Generated by Django 6.0.6 on 2026-06-16 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cleaning_type', models.CharField(choices=[('standard', 'Стандартная уборка'), ('general', 'Генеральная уборка'), ('after_repair', 'После ремонта'), ('office', 'Офисная уборка')], max_length=20, verbose_name='Тип уборки')),
                ('area_sqm', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Площадь (кв.м)')),
                ('rooms_count', models.IntegerField(default=1, verbose_name='Комнат')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('district', models.CharField(max_length=100, verbose_name='Район')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('scheduled_date', models.DateTimeField(verbose_name='Дата и время уборки')),
                ('price', models.DecimalField(decimal_places=2, editable=False, help_text='Рассчитывается автоматически: площадь × цена за м²', max_digits=10, verbose_name='Базовая цена (руб.)')),
                ('urgency', models.CharField(choices=[('normal', 'Обычный'), ('urgent', 'Срочный')], default='normal', max_length=20, verbose_name='Срочность')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус')),
                ('extra_services', models.JSONField(blank=True, default=list, help_text='Пример: [{"service": "window_cleaning", "quantity": 3}]', verbose_name='Доп. услуги')),
                ('extra_services_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Сумма доп. услуг')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Итоговая цена')),
                ('photos', models.JSONField(blank=True, null=True, verbose_name='Фотографии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_orders', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
