# Generated by Django 6.0.3 on 2026-06-17 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placement_paid_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Оплата размещения до'),
        ),
        migrations.AddField(
            model_name='order',
            name='placement_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Стоимость размещения (руб.)'),
        ),
        migrations.AddField(
            model_name='order',
            name='placement_tariff',
            field=models.CharField(blank=True, choices=[('three_days', '3 дня (25 руб)'), ('week', '1 неделя (50 руб)'), ('month', '1 месяц (150 руб)')], max_length=20, null=True, verbose_name='Тариф размещения'),
        ),
        migrations.AddField(
            model_name='order',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Опубликован'),
        ),
        migrations.AddField(
            model_name='order',
            name='urgency_fee',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Наценка за срочность'),
        ),
        migrations.AlterField(
            model_name='order',
            name='extra_services',
            field=models.JSONField(blank=True, default=list, verbose_name='Доп. услуги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Базовая цена (руб.)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('expired', 'Срок размещения истек')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Итоговая цена заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='urgency',
            field=models.CharField(choices=[('normal', 'Обычный'), ('urgent', 'Срочный (+100 руб)')], default='normal', max_length=20, verbose_name='Срочность'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (руб.)')),
                ('tariff', models.CharField(max_length=20, verbose_name='Тариф')),
                ('tariff_name', models.CharField(max_length=50, verbose_name='Название тарифа')),
                ('paid_until', models.DateTimeField(verbose_name='Оплата до')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('refunded', 'Возврат')], default='paid', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
