# Generated by Django 6.0.3 on 2026-06-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='district',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Москва', max_length=100, verbose_name='Город'),
        ),
    ]
