# Generated by Django 6.0.6 on 2026-06-15 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specializations', models.JSONField(blank=True, default=list, help_text='Список типов уборок, которые выполняет', verbose_name='Специализация')),
                ('experience_years', models.IntegerField(default='Менее года', verbose_name='Опыт работы')),
                ('about', models.TextField(blank=True, help_text='Расскажите о своих преимуществах', verbose_name='О себе')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('max_travel_distance', models.IntegerField(default=3, verbose_name='Максимальное расстояние выезда')),
                ('min_price_per_sqm', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальная цена за м²')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Рейтинг')),
                ('total_orders', models.IntegerField(default=0, verbose_name='Выполнено заказов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания профиля')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='executor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль исполнителя',
                'verbose_name_plural': 'Профили исполнителей',
            },
        ),
    ]
