# Generated by Django 6.0.6 on 2026-06-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_executorprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executorprofile',
            name='max_travel_distance',
        ),
        migrations.RemoveField(
            model_name='executorprofile',
            name='min_price_per_sqm',
        ),
    ]
