# Generated by Django 6.0.3 on 2026-06-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_executorprofile_max_travel_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executorprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Например: ул. Ленина, д. 10', max_length=255, verbose_name='Адрес (улица, дом)'),
        ),
        migrations.AddField(
            model_name='executorprofile',
            name='city',
            field=models.CharField(default='Москва', max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='executorprofile',
            name='experience_years',
            field=models.IntegerField(default=0, verbose_name='Опыт работы (лет)'),
        ),
    ]
